//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlergomuciaMVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Section", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService")]
    [System.SerializableAttribute()]
    public partial class Section : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                if ((object.ReferenceEquals(this.seccionField, value) != true)) {
                    this.seccionField = value;
                    this.RaisePropertyChanged("seccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documentos", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService")]
    [System.SerializableAttribute()]
    public partial class Documentos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDt {
            get {
                return this.CreatedDtField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDtField, value) != true)) {
                    this.CreatedDtField = value;
                    this.RaisePropertyChanged("CreatedDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Createdby {
            get {
                return this.CreatedbyField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedbyField, value) != true)) {
                    this.CreatedbyField = value;
                    this.RaisePropertyChanged("Createdby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fileID {
            get {
                return this.fileIDField;
            }
            set {
                if ((this.fileIDField.Equals(value) != true)) {
                    this.fileIDField = value;
                    this.RaisePropertyChanged("fileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filePath {
            get {
                return this.filePathField;
            }
            set {
                if ((object.ReferenceEquals(this.filePathField, value) != true)) {
                    this.filePathField = value;
                    this.RaisePropertyChanged("filePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                if ((object.ReferenceEquals(this.seccionField, value) != true)) {
                    this.seccionField = value;
                    this.RaisePropertyChanged("seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reuniones", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService.Model")]
    [System.SerializableAttribute()]
    public partial class Reuniones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resumenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enlaces {
            get {
                return this.enlacesField;
            }
            set {
                if ((object.ReferenceEquals(this.enlacesField, value) != true)) {
                    this.enlacesField = value;
                    this.RaisePropertyChanged("enlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lugar {
            get {
                return this.lugarField;
            }
            set {
                if ((object.ReferenceEquals(this.lugarField, value) != true)) {
                    this.lugarField = value;
                    this.RaisePropertyChanged("lugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resumen {
            get {
                return this.resumenField;
            }
            set {
                if ((object.ReferenceEquals(this.resumenField, value) != true)) {
                    this.resumenField = value;
                    this.RaisePropertyChanged("resumen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noticias", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService.Model")]
    [System.SerializableAttribute()]
    public partial class Noticias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string autorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resumenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                if ((object.ReferenceEquals(this.autorField, value) != true)) {
                    this.autorField = value;
                    this.RaisePropertyChanged("autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resumen {
            get {
                return this.resumenField;
            }
            set {
                if ((object.ReferenceEquals(this.resumenField, value) != true)) {
                    this.resumenField = value;
                    this.RaisePropertyChanged("resumen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulos", Namespace="http://schemas.datacontract.org/2004/07/AlergomurciaService.Model")]
    [System.SerializableAttribute()]
    public partial class Articulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resumenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaField, value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resumen {
            get {
                return this.resumenField;
            }
            set {
                if ((object.ReferenceEquals(this.resumenField, value) != true)) {
                    this.resumenField = value;
                    this.RaisePropertyChanged("resumen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllSection", ReplyAction="http://tempuri.org/IService/GetAllSectionResponse")]
        AlergomuciaMVC.ServiceReference1.Section[] GetAllSection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllSection", ReplyAction="http://tempuri.org/IService/GetAllSectionResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section[]> GetAllSectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSectionById", ReplyAction="http://tempuri.org/IService/GetSectionByIdResponse")]
        AlergomuciaMVC.ServiceReference1.Section GetSectionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSectionById", ReplyAction="http://tempuri.org/IService/GetSectionByIdResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section> GetSectionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSection", ReplyAction="http://tempuri.org/IService/AddSectionResponse")]
        AlergomuciaMVC.ServiceReference1.Section AddSection(AlergomuciaMVC.ServiceReference1.Section section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSection", ReplyAction="http://tempuri.org/IService/AddSectionResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section> AddSectionAsync(AlergomuciaMVC.ServiceReference1.Section section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        AlergomuciaMVC.ServiceReference1.Users[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Users[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDocuments", ReplyAction="http://tempuri.org/IService/GetAllDocumentsResponse")]
        AlergomuciaMVC.ServiceReference1.Documentos[] GetAllDocuments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDocuments", ReplyAction="http://tempuri.org/IService/GetAllDocumentsResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Documentos[]> GetAllDocumentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllReuniones", ReplyAction="http://tempuri.org/IService/GetAllReunionesResponse")]
        AlergomuciaMVC.ServiceReference1.Reuniones[] GetAllReuniones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllReuniones", ReplyAction="http://tempuri.org/IService/GetAllReunionesResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Reuniones[]> GetAllReunionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllNoticias", ReplyAction="http://tempuri.org/IService/GetAllNoticiasResponse")]
        AlergomuciaMVC.ServiceReference1.Noticias[] GetAllNoticias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllNoticias", ReplyAction="http://tempuri.org/IService/GetAllNoticiasResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Noticias[]> GetAllNoticiasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllArticulos", ReplyAction="http://tempuri.org/IService/GetAllArticulosResponse")]
        AlergomuciaMVC.ServiceReference1.Articulos[] GetAllArticulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllArticulos", ReplyAction="http://tempuri.org/IService/GetAllArticulosResponse")]
        System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Articulos[]> GetAllArticulosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AlergomuciaMVC.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AlergomuciaMVC.ServiceReference1.IService>, AlergomuciaMVC.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlergomuciaMVC.ServiceReference1.Section[] GetAllSection() {
            return base.Channel.GetAllSection();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section[]> GetAllSectionAsync() {
            return base.Channel.GetAllSectionAsync();
        }
        
        public AlergomuciaMVC.ServiceReference1.Section GetSectionById(int id) {
            return base.Channel.GetSectionById(id);
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section> GetSectionByIdAsync(int id) {
            return base.Channel.GetSectionByIdAsync(id);
        }
        
        public AlergomuciaMVC.ServiceReference1.Section AddSection(AlergomuciaMVC.ServiceReference1.Section section) {
            return base.Channel.AddSection(section);
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Section> AddSectionAsync(AlergomuciaMVC.ServiceReference1.Section section) {
            return base.Channel.AddSectionAsync(section);
        }
        
        public AlergomuciaMVC.ServiceReference1.Users[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Users[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public AlergomuciaMVC.ServiceReference1.Documentos[] GetAllDocuments() {
            return base.Channel.GetAllDocuments();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Documentos[]> GetAllDocumentsAsync() {
            return base.Channel.GetAllDocumentsAsync();
        }
        
        public AlergomuciaMVC.ServiceReference1.Reuniones[] GetAllReuniones() {
            return base.Channel.GetAllReuniones();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Reuniones[]> GetAllReunionesAsync() {
            return base.Channel.GetAllReunionesAsync();
        }
        
        public AlergomuciaMVC.ServiceReference1.Noticias[] GetAllNoticias() {
            return base.Channel.GetAllNoticias();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Noticias[]> GetAllNoticiasAsync() {
            return base.Channel.GetAllNoticiasAsync();
        }
        
        public AlergomuciaMVC.ServiceReference1.Articulos[] GetAllArticulos() {
            return base.Channel.GetAllArticulos();
        }
        
        public System.Threading.Tasks.Task<AlergomuciaMVC.ServiceReference1.Articulos[]> GetAllArticulosAsync() {
            return base.Channel.GetAllArticulosAsync();
        }
    }
}
